In [2]:
def my_func():
    print("Hello world!")

In [4]:
my_func()

Hello world!


In [6]:
def add(a, b):
    if a > 2:
        print(a + b)
    else: 
        print("a 2'den küçük")
    

In [8]:
add(1, 4)

a 2'den küçük


In [10]:
add(8, 1)

9


In [12]:
def sum(a, b):
    sum = a + b
    return sum

In [14]:
a = sum(2,3)

In [16]:
a

5

In [18]:
x = a + 10

In [20]:
x

15

In [22]:
def func(a, b= 5, c= 10):
    print("a eşittir", a, "b eşittir", b, "c eşittir", c)

In [24]:
func(1, 6, 11)

a eşittir 1 b eşittir 6 c eşittir 11


In [26]:
def say(message, times = 2):
    print(message * times)

In [28]:
say(2, 10)

20


In [30]:
def total(a = 5, *numbers, **phone_book):
    for single_items in numbers:
        print("single items", single_items)
    for key , value in phone_book.items():
        print(key, value)
    print("a=", a)

In [32]:
total(10, 2, 4, 6, 15, 30, Jack = 18, Brady = 25, Kim = 35)

single items 2
single items 4
single items 6
single items 15
single items 30
Jack 18
Brady 25
Kim 35
a= 10


In [34]:
#lambda fonksiyonları

In [36]:
sum_lambda = lambda x ,y: x + y

In [38]:
g = sum_lambda(2, 5)

In [40]:
g

7

In [42]:
v = 10

In [44]:
sum_lambda(v, 5)

15

In [46]:
def create_string():
    new_string = "yeni string"
    print(new_string)

In [48]:
create_string()

yeni string


In [50]:
print(new_string)

NameError: name 'new_string' is not defined

In [ ]:
def create_string():
    global new_string
    new_string = "yeni string"
    print(new_string)

In [53]:
create_string()

yeni string


In [55]:
print(new_string)

NameError: name 'new_string' is not defined

In [57]:
x = 5 
y = 19

def sum():
    print(x+ y)

In [59]:
sum()

24


In [61]:
x = 5 
y = 19

def sum():
    global x
    x = x + y
    print(f"x= {x}, y= {y}")

In [63]:
print(f"fonksiyonu çalıştırmadan önce x = {x}, y = {y}")

sum()

print(f"fonksiyonu çalıştırdıktan sonra x = {x}, y = {y}")

fonksiyonu çalıştırmadan önce x = 5, y = 19
x= 24, y= 19
fonksiyonu çalıştırdıktan sonra x = 24, y = 19


In [65]:
x

24

In [68]:
new_string = "new"

In [70]:
def create_string():
    new_string = "yeni string"
    return new_string

In [72]:
create_string()

'yeni string'

In [74]:
a = create_string()

In [76]:
a

'yeni string'

In [78]:
new_string

'new'

In [80]:
def create_string():
    global new_string
    new_string = "yeni string"
    return new_string
    

In [82]:
a = create_string()

In [84]:
print(a)

yeni string


In [86]:
new_string

'yeni string'

# Kütüphaneler

In [89]:
import math

In [91]:
print(math.sqrt(16))

4.0


In [93]:
from math import sqrt

In [95]:
sqrt(64)

8.0

In [97]:
import math as m

In [99]:
print(m.sqrt(64))

8.0


In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [110]:
# !pip3 install numpy

## numpy

In [113]:
import numpy as np

In [115]:
a = np.array([1,2,3,4,5])

In [117]:
a

array([1, 2, 3, 4, 5])

In [119]:
print(a)

[1 2 3 4 5]


In [121]:
a[0]

1

In [123]:
m = np.array([[1,2,3], [4,5,6]])

In [125]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
a = np.array([1.3,2.6,3,4,5],dtype = float)
m = np.array([[1,2,3],[4,5,6]],dtype = int)

In [129]:
print(a.shape)

(5,)


In [131]:
print(m.shape)

(2, 3)


In [133]:
print(m.ndim)

2


In [135]:
print(a.size)
print(m.size)

5
6


In [137]:
print(a.dtype)
print(m.dtype)

float64
int32


In [139]:
print(a.itemsize)
print(m.itemsize)

8
4


In [141]:
a = np.ones((5,))

In [143]:
a

array([1., 1., 1., 1., 1.])

In [145]:
m = np.ones((2,3), dtype = int)

In [147]:
m

array([[1, 1, 1],
       [1, 1, 1]])

In [149]:
a = np.zeros((5,))

In [151]:
a

array([0., 0., 0., 0., 0.])

In [153]:
m = np.zeros((5,5), dtype = int)
print(m)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [155]:
i = np.identity(20, dtype = int)

In [157]:
i

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [159]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [161]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


In [163]:
a = np.random.random(3)

In [165]:
a

array([0.74681366, 0.01493174, 0.15689533])

In [167]:
a = np.random.random((3,4))
print(a)

[[0.84833741 0.70983377 0.64898308 0.74091921]
 [0.56065295 0.83463478 0.93371731 0.46207854]
 [0.00988382 0.09795228 0.45166527 0.73508481]]


In [169]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [171]:
a[5]

5

In [173]:
print(a[1:4])

[1 2 3]


In [175]:
print(a[1:])

[1 2 3 4 5 6 7 8 9]


In [177]:
print(a[:5])

[0 1 2 3 4]


In [179]:
print(a[2:6])

[2 3 4 5]


In [181]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [183]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
print(m[2,1])

8


In [187]:
print(m[0:,1])

[2 5 8]


In [189]:
print(m[1:,1])

[5 8]


In [191]:
print(m[1,1:])

[5 6]


In [193]:
print(m[2,1:])

[8 9]


In [195]:
print(m[1:,1])

[5 8]


In [197]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [199]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(a + b)

[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]


In [201]:
print(a - b)
print(a * b)
print(a / b)

[[-1  0  1]
 [ 1  2  3]
 [ 3  4  5]]
[[ 2  4  6]
 [12 15 18]
 [28 32 36]]
[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]
 [1.75       2.         2.25      ]]


In [203]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[0 0 0]
 [3 3 3]
 [6 6 6]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[1.  1.  1. ]
 [4.  2.5 2. ]
 [7.  4.  3. ]]


In [205]:
a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

1
5
15
3.0
120


In [207]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.prod())

1
9
45
5.0
362880


In [209]:
print(a.mean())

5.0


In [211]:
type(a)

numpy.ndarray

## Pandas

In [214]:
import pandas as pd

In [216]:
# series - dataframe

In [218]:
mountains_height = pd.Series([2061, 2035.8, 2028.5, 2022.5, 2016.4])

In [220]:
mountains_height

0    2061.0
1    2035.8
2    2028.5
3    2022.5
4    2016.4
dtype: float64

In [222]:
mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

In [224]:
mountains_height

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros            2022.5
Gutin_Tomnatik    2016.4
Name: Height, m, dtype: float64

In [226]:
print(mountains_height[2])

2028.5


In [228]:
print(mountains_height["Pip_Ivan"])

2028.5


In [230]:
print(mountains_height[["Pip_Ivan","Petros","Goverla"]])

Pip_Ivan    2028.5
Petros      2022.5
Goverla     2061.0
Name: Height, m, dtype: float64


In [232]:
print(mountains_height[1:3])

Brebenskyl    2035.8
Pip_Ivan      2028.5
Name: Height, m, dtype: float64


In [234]:
print(mountains_height["Pip_Ivan":"Gutin_Tomnatik"])

Pip_Ivan          2028.5
Petros            2022.5
Gutin_Tomnatik    2016.4
Name: Height, m, dtype: float64


In [236]:
mountains_height = pd.Series(
    data=[2061, 2035.8, 2028.5, 2022.5, 2016.4],
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

In [238]:
mountains_height

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros            2022.5
Gutin_Tomnatik    2016.4
Name: Height, m, dtype: float64

In [240]:
print(mountains_height > 2030)

Goverla            True
Brebenskyl         True
Pip_Ivan          False
Petros            False
Gutin_Tomnatik    False
Name: Height, m, dtype: bool


In [242]:
print(mountains_height[mountains_height > 2030])

Goverla       2061.0
Brebenskyl    2035.8
Name: Height, m, dtype: float64


In [244]:
print("Goverla" in mountains_height)

True


In [246]:
#inplace = False
#ascending = True

In [248]:
mountains_height = mountains_height.sort_index(ascending = False)
print(mountains_height)

Pip_Ivan          2028.5
Petros            2022.5
Gutin_Tomnatik    2016.4
Goverla           2061.0
Brebenskyl        2035.8
Name: Height, m, dtype: float64


In [250]:
mountains_height.sort_index(inplace = True)
print(mountains_height)

Brebenskyl        2035.8
Goverla           2061.0
Gutin_Tomnatik    2016.4
Petros            2022.5
Pip_Ivan          2028.5
Name: Height, m, dtype: float64


In [252]:
mountains_height.sort_values(inplace = True, ascending = True)
print(mountains_height)

Gutin_Tomnatik    2016.4
Petros            2022.5
Pip_Ivan          2028.5
Brebenskyl        2035.8
Goverla           2061.0
Name: Height, m, dtype: float64


In [254]:
mountains_height = pd.Series(
    {"Goverla": 2061, "Brebenskyl": 2035.8, "Pip_Ivan": 2028.5},
    index=["Goverla", "Brebenskyl", "Pip_Ivan", "Petros", "Gutin_Tomnatik"],
    name="Height, m",
    dtype=float,
)

print(mountains_height)

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros               NaN
Gutin_Tomnatik       NaN
Name: Height, m, dtype: float64


In [256]:
mountains_height.fillna(436, inplace=True)

In [258]:
mountains_height

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros             436.0
Gutin_Tomnatik     436.0
Name: Height, m, dtype: float64

In [260]:
mountains_height = mountains_height.fillna(0)

In [262]:
mountains_height

Goverla           2061.0
Brebenskyl        2035.8
Pip_Ivan          2028.5
Petros             436.0
Gutin_Tomnatik     436.0
Name: Height, m, dtype: float64

## Dataframe

In [265]:
#dictionary
data = {'ID': [1, 2], 'Name': ['Alice', 'Bob']}
df = pd.DataFrame(data)
print(df)

   ID   Name
0   1  Alice
1   2    Bob


In [267]:
#list
data = [[1, 'Alice'], [2, 'Bob']]
df = pd.DataFrame(data, columns=['ID', 'Name'])
print(df)

   ID   Name
0   1  Alice
1   2    Bob


In [269]:
#numpy array
data = np.array([[1, 'Alice'], [2, 'Bob']])
df = pd.DataFrame(data, columns=['ID', 'Name'])
print(df)

  ID   Name
0  1  Alice
1  2    Bob


In [271]:
df.shape

(2, 2)

In [273]:
print(df.columns)

Index(['ID', 'Name'], dtype='object')


In [275]:
print(df.index)

RangeIndex(start=0, stop=2, step=1)


In [277]:
print(df.dtypes)

ID      object
Name    object
dtype: object


In [279]:
contacts = pd.DataFrame(
    {
        "name": [
            "Allen Raymond",
            "Chaim Lewis",
            "Kennedy Lane",
            "Wylie Pope",
            "Cyrus Jackson",
        ],
        "email": [
            "nulla.ante@vestibul.co.uk",
            "dui.in@egetlacus.ca",
            "mattis.Cras@nonenimMauris.net",
            "est@utquamvel.net",
            "nibh@semsempererat.com",
        ],
        "phone": [
            "(992) 914-3792",
            "(294) 840-6685",
            "(542) 451-7038",
            "(692) 802-2949",
            "(501) 472-5218",
        ],
        "favorite": [False, False, True, False, True],
    },
    index=[1, 2, 3, 4, 5],
)

print(contacts)

            name                          email           phone  favorite
1  Allen Raymond      nulla.ante@vestibul.co.uk  (992) 914-3792     False
2    Chaim Lewis            dui.in@egetlacus.ca  (294) 840-6685     False
3   Kennedy Lane  mattis.Cras@nonenimMauris.net  (542) 451-7038      True
4     Wylie Pope              est@utquamvel.net  (692) 802-2949     False
5  Cyrus Jackson         nibh@semsempererat.com  (501) 472-5218      True


In [281]:
contacts.shape

(5, 4)

In [283]:
contacts["name"]

1    Allen Raymond
2      Chaim Lewis
3     Kennedy Lane
4       Wylie Pope
5    Cyrus Jackson
Name: name, dtype: object

In [285]:
contacts.loc[5]

name                 Cyrus Jackson
email       nibh@semsempererat.com
phone               (501) 472-5218
favorite                      True
Name: 5, dtype: object

In [287]:
contacts.iloc[4]

name                 Cyrus Jackson
email       nibh@semsempererat.com
phone               (501) 472-5218
favorite                      True
Name: 5, dtype: object

In [289]:
contacts[2:4]

name                          email           phone  favorite
3  Kennedy Lane  mattis.Cras@nonenimMauris.net  (542) 451-7038      True
4    Wylie Pope              est@utquamvel.net  (692) 802-2949     False

In [291]:
contacts

name                          email           phone  favorite
1  Allen Raymond      nulla.ante@vestibul.co.uk  (992) 914-3792     False
2    Chaim Lewis            dui.in@egetlacus.ca  (294) 840-6685     False
3   Kennedy Lane  mattis.Cras@nonenimMauris.net  (542) 451-7038      True
4     Wylie Pope              est@utquamvel.net  (692) 802-2949     False
5  Cyrus Jackson         nibh@semsempererat.com  (501) 472-5218      True

In [293]:
contacts[contacts['favorite'] == True]

name                          email           phone  favorite
3   Kennedy Lane  mattis.Cras@nonenimMauris.net  (542) 451-7038      True
5  Cyrus Jackson         nibh@semsempererat.com  (501) 472-5218      True

In [295]:
# & | 
contacts[(contacts['favorite'] == True)|(contacts['name'] == 'Allen Raymond')]

name                          email           phone  favorite
1  Allen Raymond      nulla.ante@vestibul.co.uk  (992) 914-3792     False
3   Kennedy Lane  mattis.Cras@nonenimMauris.net  (542) 451-7038      True
5  Cyrus Jackson         nibh@semsempererat.com  (501) 472-5218      True

In [297]:
contacts[(contacts['favorite'] == False)&(contacts['name'] == 'Allen Raymond')]

name                      email           phone  favorite
1  Allen Raymond  nulla.ante@vestibul.co.uk  (992) 914-3792     False